pipeline {
    agent any
    tools {
        gradle 'gradle'
    }
    stages {
        stage('Git Clone') {
            steps {
                dir('/var/jenkins_home/workspace/Gokk2_Senior'){
                    sh '''
                        echo delete existing project file 
                    '''
                    deleteDir()
                }
                checkout scmGit(
                    branches: [[name: '*/master']], 
                    extensions: [
                        submodule(
                            parentCredentials: true, 
                            reference: '', 
                            trackingSubmodules: true
                        )
                    ],
                    userRemoteConfigs: [
                        [
                            credentialsId: 'jenkins',
                            url: 'https://lab.ssafy.com/s09-final/S09P31D105.git'
                        ],
                   ])
                }
        }
        stage('BE-Build') {
            steps {
                dir("./BE/seniorNaver") {
                    sh "chmod +x ./gradlew"
                    sh "./gradlew clean build"
                }
            }
        }
        stage('Deploy') {
            steps {
                dir("./BE/seniorNaver") {
                    sh "docker-compose up -d --build"
                }
            }
        }
        stage('Clean Up') {
            steps {
                sh "docker image prune -f"
            }
        }
    }
}
